### ISSUE TITLE
TinyTds::Error (Adaptive Server connection failed)

### ISSUE THREAD

**Issue by monteirobrena** [rails-sqlserver/tiny_tds#266]
I'm trying to connect my Rails project in Ubuntu with my database SQL Server in Azure.

In my server, when I access my project folder and run `rails s` I can connect with my database and everything work fine. But, if I run my project with Puma and Nginx, I receive this error:

`TinyTds::Error (Adaptive Server connection failed):`

This is my `config/database.yml`:

```
staging:
  adapter: sqlserver
  host: db-project.database.windows.net
  database: db-project
  username: user@db-project
  password: password
  port: 1433
  azure: true
```

The same error occurred when I try make a deploy with Capistrano and run `rake db:migrate`.

Any help? Thank you.
