### ISSUE TITLE
ActiveRecord::StatementInvalid (TinyTds::Error: Invalid column prefix '': No table name specified) Rails 6

### ISSUE THREAD

**Issue by RailsCod3rFuture** [rails-sqlserver/tiny_tds#477]
I'm attempting to use rails 6 new read-only database functionality with tiny_tds. The issue i am having is that it thinks no table name exist for the model I am trying to connect with for a remote SQLEXPRESS Server.

My setup is below
**remote_file.rb** / **remote_files table**

```
class RemoteFile < ApplicationRecord
  self.abstract_class = true
  connects_to database: {reading: :remote_files}
end

```
**database.yml**

```
production:
    primary:
         adapter: postgresl
       ....
    ...
   remote_files:
       adapter: sqlserver
       database: RemoteData
       dataserver: 12........:5171\SQLEXPRESS
       username: rails-guy
       password: ergegegegegege

```

I'm able to connect to the server without issue, outside of rails. But, why does this error pop up when I use the code below?

```
Activerecord::Base.connected_to(database: {reading: :remote_files}) do 
 RemoteFile.first
end


```
